
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  
  RouteTables: # for gateway type
    Type: CommaDelimitedList
  
  Subnets: # for interface type
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup: # for interface type
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  #
  # VPC Endpoint - Gateway Type
  #
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      RouteTableIds: !Ref RouteTables
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway # Gateway, GatewayLoadBalancer, Interface
      VpcId: !Ref VpcId

  #
  # VPC Endpoint - Interface Type
  #
  S3InterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PrivateDnsEnabled: false # s3 can not support, but its recommended other service.
      SubnetIds:  !Ref Subnets
      SecurityGroupIds: 
        - !Ref SecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Interface # Gateway, GatewayLoadBalancer, Interface
      VpcId: !Ref VpcId