
Resources:
  #
  # ECR - Repository
  #
  Repository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: example-repository
      EncryptionConfiguration: 
        EncryptionType: KMS # AES256 , KMS
        # KmsKey: String
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE # IMMUTABLE , MUTABLE
      # LifecyclePolicy: 
      #   LifecyclePolicyText: String
      #   RegistryId: String
      # RepositoryPolicyText: Json
      Tags: 
        - Key: key01
          Value: value01
