
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The VPC id for efs network interfaces"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The Subnet Ids for efs network interfaces"

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "The Security Group Ids for efs network interfaces"

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: Unicorn.Rental

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

Resources:
  #
  # EFS - FileSystem
  #
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      BackupPolicy: 
        Status: ENABLED
      Encrypted: true
      # KmsKeyId: String
      FileSystemTags: 
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: Unicorn-efs
      LifecyclePolicies: 
        - TransitionToIA: 'AFTER_30_DAYS' # AFTER_7_DAYS , AFTER_14_DAYS , AFTER_30_DAYS , AFTER_60_DAYS , AFTER_90_DAYS
        - TransitionToPrimaryStorageClass: 'AFTER_1_ACCESS'
      PerformanceMode: generalPurpose # generalPurpose , maxIO
      ThroughputMode: bursting # bursting , provisioned
      # ProvisionedThroughputInMibps: Double
      FileSystemPolicy:
        Version: "2012-10-17"
        Id: "EfsPolicy"
        Statement:
          - Sid: "PreventRootAccessByDefault"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "elasticfilesystem:ClientWrite"
              - "elasticfilesystem:ClientMount"
            Condition:
              Bool:
                "elasticfilesystem:AccessedViaMountTarget": "true"
          - Sid: "DenyInsecureTransport"
            Effect: "Deny"
            Principal:
              AWS: "*"
            Action: "*"
            Condition:
              Bool:
                "aws:SecureTransport": "false"
  
  #
  # EFS - MountTarget
  #
  MountTargetA:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref FileSystem
      # IpAddress: String
      SecurityGroups: !Ref SecurityGroupIds
      SubnetId: !Select [ 0 , !Ref SubnetIds ]

  MountTargetB:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref FileSystem
      # IpAddress: String
      SecurityGroups: !Ref SecurityGroupIds
      SubnetId: !Select [ 1 , !Ref SubnetIds ]
  
  MountTargetC:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref FileSystem
      # IpAddress: String
      SecurityGroups: !Ref SecurityGroupIds
      SubnetId: !Select [ 2 , !Ref SubnetIds ]