
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The vpc id for associated NACL"

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The subnet of public for associated NACL"
  
  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: Unicorn.Rental

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

  NamePrefix:
    Type: String
    Description: "The prefix of resource's Name tag"
    Default: Unicorn

Resources:
  #
  # NACL
  #
  Public:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: !Ref VpcId
      Tags: 
        - Key: Name
          Value: !Sub '${NamePrefix}-public-nacl'
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
  
  #
  # NACL - Ingress Entry
  #
  PublicIngressEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      NetworkAclId: !Ref Public
      Egress: false
      CidrBlock: 0.0.0.0/0
      Protocol: -1 # -1(all), 1(ICMP), 6(TCP), 17(UDP)
      # PortRange: 
      #   From: 0
      #   To: 65535
      RuleAction: allow # allow , deny
      RuleNumber: 10
  
  PublicIngressEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      NetworkAclId: !Ref Public
      Egress: false
      CidrBlock: 0.0.0.0/0
      Protocol: 6 # -1(all), 1(ICMP), 6(TCP), 17(UDP)
      PortRange: 
        From: 1024
        To: 65535
      RuleAction: allow # allow , deny
      RuleNumber: 20

  #
  # NACL - Egress Entry
  #
  PublicEgressEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      NetworkAclId: !Ref Public
      Egress: true
      CidrBlock: 0.0.0.0/0
      Protocol: -1 # -1(all), 1(ICMP), 6(TCP), 17(UDP)
      # PortRange: 
      #   From: 0
      #   To: 65535
      RuleAction: allow # allow , deny
      RuleNumber: 10
  
  PublicEgressEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      NetworkAclId: !Ref Public
      Egress: true
      CidrBlock: 0.0.0.0/0
      Protocol: 6 # -1(all), 1(ICMP), 6(TCP), 17(UDP)
      PortRange: 
        From: 1024
        To: 65535
      RuleAction: allow # allow , deny
      RuleNumber: 20
  
  #
  # NACL - Association subnets
  #
  AssociationPublicSubnetA:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref Public
      SubnetId: !Select [ 0, !Ref PublicSubnetIds ]
  
  AssociationPublicSubnetB:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref Public
      SubnetId: !Select [ 1, !Ref PublicSubnetIds ]
  
  AssociationPublicSubnetC:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref Public
      SubnetId: !Select [ 2, !Ref PublicSubnetIds ]