
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The VPC id associated security group"

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: Unicorn.Rental

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

  NamePrefix:
    Type: String
    Description: "The prefix of resource's Name tag"
    Default: Unicorn


Resources:
  #
  # Security Groups
  #
  App:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "The security group for attached App"
      GroupName: !Sub '${NamePrefix}-app-sg'
      VpcId: !Ref VpcId
      Tags: 
        - Key: Name
          Value: !Sub '${NamePrefix}-app-sg'
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
    
  #
  # Ingress Rules
  #
  AppIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      Description: "allow all traffic from anywhere"
      GroupId: !Ref App
      # SourceSecurityGroupId: !Ref App
      # SourcePrefixListId: pl-63a5400a # you can check prefixlistID in console.
      CidrIp: 0.0.0.0/0
      IpProtocol: -1 # -1(all) , tcp , udp , icmp , icmpv6
      # FromPort: 443
      # ToPort: 443

  #
  # Egress Rules
  #
  AppEgress1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties: 
      Description: "allow all traffic to anywhere"
      GroupId: !Ref App
      # DestinationSecurityGroupId: !Ref App
      CidrIp: 0.0.0.0/0
      IpProtocol: -1 # -1(all) , tcp , udp , icmp , icmpv6
      # FromPort: 443
      # ToPort: 443
