
Parameters:
  ClusterName:
    Description: 'The cluster name of eks'
    Type: String
    
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The Subnet Ids for launched instances"

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "The Security Group Ids for launched instances"

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "The Keypair for launched instances"
  
  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: Unicorn.Rental

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

  ClusterName:
    Type: String
    Description: "The name of eks cluster"

  NodeGroupName:
    Type: String
    Description: "The name of node group"

Resources:
  #
  # IAM Role (For EKS Node Group)
  #
  Role:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub '${NodeGroupName}-role'
      # Description: description
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - ec2.amazonaws.com
      # Policies: 
      #   - PolicyName: dynamodb-query
      #     PolicyDocument:
      #       Version: "2012-10-17"
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - 'dynamodb:Query'
      #             - 'dynamodb:Scan'
      #           Resource: '*'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy        
      Tags: 
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner

  #
  # EC2 - Launch Template
  #
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      # LaunchTemplateName: example-eks-nodegroup-lt
      LaunchTemplateData: 
        BlockDeviceMappings: 
          - DeviceName: /dev/xvda
            Ebs: 
              DeleteOnTermination: true
              VolumeType: gp3
              VolumeSize: 20
              Iops: 3000
              Throughput: 125
              Encrypted: true
              # KmsKeyId: String
        # InstanceInitiatedShutdownBehavior: terminate # stop , terminate
        InstanceType: c5.xlarge
        KeyName: !Ref KeyPair
        # Monitoring: 
        SecurityGroupIds: !Ref SecurityGroupIds
        TagSpecifications: 
          - ResourceType: instance # instance, volume
            Tags: 
              - Key: Name
                Value: !Ref NodeGroupName
              - Key: Project
                Value: !Ref Project
              - Key: Owner
                Value: !Ref Owner
          - ResourceType: volume # instance, volume
            Tags: 
              - Key: Name
                Value: !Ref NodeGroupName
              - Key: Project
                Value: !Ref Project
              - Key: Owner
                Value: !Ref Owner

  #
  # EKS - Managed Node Group
  #
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties: 
      NodegroupName: !Ref NodeGroupName
      AmiType: BOTTLEROCKET_x86_64 # AL2_ARM_64 | AL2_x86_64 | AL2_x86_64_GPU | BOTTLEROCKET_ARM_64 | BOTTLEROCKET_x86_64 | CUSTOM
      CapacityType: ON_DEMAND # ON_DEMAND | SPOT
      ClusterName: !Ref ClusterName
      ForceUpdateEnabled: false
      LaunchTemplate: 
        Id: !Ref LaunchTemplate
        # Name: String
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      NodeRole: !GetAtt Role.Arn
      ScalingConfig: 
        DesiredSize: 3 # It must be defined at first time. and after that it is recommended removing.
        MinSize: 3
        MaxSize: 20
      Subnets: !Ref SubnetIds
      UpdateConfig: 
        # MaxUnavailable: 100
        MaxUnavailablePercentage: 100
      Tags:
        Project: !Ref Project
        Owner: !Ref Owner
      # Labels:
      #   Management: Apps
      Taints: 
        - Effect: NO_SCHEDULE # NO_EXECUTE | NO_SCHEDULE | PREFER_NO_SCHEDULE
          Key: Management
          Value: Apps
