
Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: Unicorn.Rental

  NamePrefix:
    Type: String
    Description: "The prefix of resource's Name tag"
    Default: Unicorn

Resources:
  #
  # IAM - Role (for RDS Monitoring)
  #
  MonitoringRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${NamePrefix}-aurora-mysql-monitoring-role'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole'
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'monitoring.rds.amazonaws.com'
          Action: 'sts:AssumeRole'
  
  #
  # Secrets Manager - Secret
  #
  MasterUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${NamePrefix}-aurora-mysql-cluster/admin'
      Description: 'This is secret of rds username and password'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        ExcludeCharacters: '"@/\'
        PasswordLength: 16

  #
  # Secrets Manager - TargetAttachment
  #
  MasterUserSecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MasterUserSecret
      TargetId: !Ref DBCluster
      TargetType: AWS::RDS::DBCluster

  #
  # RDS - Cluster Parameter Group
  #
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties: 
      Description: 'This is cluster parameter group of aurora-mysql5.7'
      Family: aurora-mysql5.7
      Parameters:
        time_zone: US/Eastern
        character_set_database: utf8mb4

  #
  # RDS - Parameter Group
  #
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: 'This is parameter group of aurora-mysql5.7'
      Family: aurora-mysql5.7
      # Parameters: 
      #   Key : Value

  #
  # RDS - Subnet Group
  #
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: 'This is subnet group of example'
      DBSubnetGroupName: !Sub '${NamePrefix}-aurora-mysql-subnetgroup'
      SubnetIds: !Ref SubnetIds
  
  #
  # RDS - DBCluster
  #
  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Properties: 
      DBClusterIdentifier: !Sub '${NamePrefix}-aurora-mysql-cluster'
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql # aurora (mysql5.6) , aurora-mysql (mysql5.7) , aurora-postgresql
      EngineMode: provisioned # provisioned , serverless , parallelquery , global , multimaster
      EngineVersion: 5.7.mysql_aurora.2.10.2
      EnableCloudwatchLogsExports: # audit , error , general , slowquery
        - audit
        - error
        - general
        - slowquery
      EnableIAMDatabaseAuthentication: true
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MasterUserSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MasterUserSecret, ':SecretString:password}}' ]]
      Port: 3306
      DeletionProtection: false
      # BacktrackWindow: 24 # hours
      BackupRetentionPeriod: 7 # days
      CopyTagsToSnapshot: true
      # PreferredBackupWindow: String
      # PreferredMaintenanceWindow: String
      StorageEncrypted: true
      # KmsKeyId: String
      VpcSecurityGroupIds: !Ref SecurityGroupIds
      DatabaseName: exampledb
      Tags: 
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner

  #
  # RDS - DBInstance (first)
  #
  DBInstance1:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties: 
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Sub '${NamePrefix}-aurora-mysql-instance-1'
      Engine: aurora-mysql
      # EngineVersion: 5.7.mysql_aurora.2.10.2
      DBInstanceClass: db.r6g.large
      DBParameterGroupName: !Ref DBParameterGroup
      PubliclyAccessible: false
      MonitoringInterval: 60 # 0 , 1 , 5 , 10 , 15 , 30 , 60
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      DeleteAutomatedBackups: false    
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      Tags: 
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
      
  #
  # RDS - DBInstance (second)
  #
  DBInstance2:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties: 
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Sub '${NamePrefix}-aurora-mysql-instance-2'
      Engine: aurora-mysql
      # EngineVersion: 5.7.mysql_aurora.2.10.2
      DBInstanceClass: db.r6g.large
      DBParameterGroupName: !Ref DBParameterGroup
      PubliclyAccessible: false
      MonitoringInterval: 60 # 0 , 1 , 5 , 10 , 15 , 30 , 60
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      DeleteAutomatedBackups: false    
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      Tags: 
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner