
Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>

  OwnerTeamName:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

  ProjectName:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsscc2022

  Prefix:
    Type: String
    Description: "The prefix of resource's Name tag"
    Default: useast1-wsscc2022

Resources:
  #
  # Cloudwatch Logs - Log Group
  #
  ElasticacheLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/elasticache/${Prefix}-redis-cluster'
      RetentionInDays: 7 # days
  
  #
  # Elasticache - Parameter Group
  #
  ElasticacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties: 
      # memcached1.4 | memcached1.5 | memcached1.6 
      # redis2.6 | redis2.8 | redis3.2 | redis4.0 | redis5.0 | redis6.x
      CacheParameterGroupFamily: redis6.x
      Description: "This is redis cluster parameter group"
      Properties: 
        cluster-enabled: 'yes'

  #
  # Elasticache - Subnet Group
  #
  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      CacheSubnetGroupName: !Sub '${Prefix}-redis-cluster-subnetgroup'
      Description: "This is redis cluster subnet group"
      SubnetIds: !Ref SubnetIds

  #
  # Elasticache - Replication Group
  #
  ElasticacheReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    DeletionPolicy: Delete
    Properties: 
      ReplicationGroupId: !Sub '${Prefix}-redis-cluster'
      ReplicationGroupDescription: "This is Elasticache Redis (cluster mode enabled)"
      Engine: redis # memcached | redis
      EngineVersion: '6.2'  # aws elasticache describe-cache-engine-versions
      CacheNodeType: cache.m6g.large
      NumNodeGroups: 3 # shard number
      ReplicasPerNodeGroup: 2
      Port: 6379
      CacheParameterGroupName: !Ref ElasticacheParameterGroup
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup
      SecurityGroupIds: !Ref SecurityGroupIds
      MultiAZEnabled: true
      AutomaticFailoverEnabled: true
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      # KmsKeyId: String
      # AuthToken: String
      AutoMinorVersionUpgrade: true
      # SnapshotWindow: String
      SnapshotRetentionLimit: 1
      # DataTieringEnabled: Boolean
      LogDeliveryConfigurations: 
        - DestinationDetails: 
            CloudWatchLogsDetails: 
              LogGroup:  !Ref ElasticacheLogGroup
          DestinationType: cloudwatch-logs # cloudwatch-logs | kinesis-firehose
          LogFormat: json # json | text
          LogType: slow-log # slow-log | engine-log
        - DestinationDetails: 
            CloudWatchLogsDetails: 
              LogGroup: !Ref ElasticacheLogGroup
          DestinationType: cloudwatch-logs # cloudwatch-logs | kinesis-firehose
          LogFormat: json # json | text
          LogType: engine-log # slow-log | engine-log
      # SnapshotArns: 
      #   - String
      # UserGroupIds: 
      #   - String
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: owner:team
          Value: !Ref OwnerTeamName