
Parameters:
  SubnetId:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  
  AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  
  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: Unicorn.Rental

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

  InstanceName:
    Type: String
    Description: "The name(tag) of ec2 instance"
    Default: Unicorn-app-ec2

Resources:
  #
  # IAM Role
  #
  Role:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub '${InstanceName}-role'
      Description: !Sub "The role of ec2 instance, ${InstanceName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - ec2.amazonaws.com
      # Policies: 
      #   - PolicyName: dynamodb-query
      #     PolicyDocument:
      #       Version: "2012-10-17"
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - 'dynamodb:Query'
      #             - 'dynamodb:Scan'
      #           Resource: '*'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Tags: 
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
  
  #
  # IAM Instance Profile
  #
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: Role
    Properties: 
      # InstanceProfileName: example-ec2-instance-profile
      Path: /
      Roles: 
        - !Ref Role

  #
  # EC2 - Instance
  #
  Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t3.small
      BlockDeviceMappings: 
        - DeviceName: /dev/xvda
          Ebs: 
            DeleteOnTermination: true
            Encrypted: true
            # KmsKeyId: String
            VolumeType: gp3
            VolumeSize: 10
            Iops: 3000
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref AMI
      KeyName: !Ref KeyPair
      InstanceInitiatedShutdownBehavior: terminate # stop , terminate
      Monitoring: true # detailed monitoring
      SubnetId: !Ref SubnetId
      SecurityGroupIds: !Ref SecurityGroupIds
      PropagateTagsToVolumeOnCreation: true
      Tags: 
        - Key: Name
          Value: !Ref InstanceName
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner