
Parameters:
  SourceVPC:
    Type: AWS::EC2::VPC::Id

  TargetVPC:
    Type: AWS::EC2::VPC::Id

  ProjectName:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsscc2022

  OwnerTeamName:
    Type: String
    Description: "The team name for owned this resources"
    Default: TeamKorea

Resources:
  #
  # VPC - PeeringConnection
  #
  VpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      # PeerOwnerId: String
      PeerRegion: us-east-1
      # PeerRoleArn: String
      PeerVpcId: !Ref TargetVPC
      VpcId: !Ref SourceVPC
      Tags: 
        - Key: Name
          Value: !Sub '${ProjectName}-vpc-peering'
        - Key: account
          Value: !Ref AWS::AccountId
        - Key: region
          Value: !Ref AWS::Region
        - Key: project
          Value: !Ref ProjectName
        - Key: owner:team
          Value: !Ref OwnerTeamName