
Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>

Resources:
  #
  # Elasticache - Parameter Group
  #
  ElasticacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties: 
      # memcached1.4 | memcached1.5 | memcached1.6 
      # redis2.6 | redis2.8 | redis3.2 | redis4.0 | redis5.0 | redis6.x
      CacheParameterGroupFamily: memcached1.6
      Description: This is memcached parameter group
      # Properties: 
      #   cluster-enabled: 'no'

  #
  # Elasticache - Subnet Group
  #
  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      # CacheSubnetGroupName: String
      Description: This is memcached subnet group
      SubnetIds: !Ref SubnetIds

  #
  # Elasticache - Redis Cluster
  #
  ElasticacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties: 
      ClusterName: example-memcached-cluster
      Engine: memcached # memcached | redis
      EngineVersion: '1.6.6' # aws elasticache describe-cache-engine-versions
      CacheNodeType: cache.m6g.large
      NumCacheNodes: 3
      Port: 11211
      CacheParameterGroupName: !Ref ElasticacheParameterGroup
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup
      AZMode: cross-az # cross-az | single-az
      AutoMinorVersionUpgrade: true
      VpcSecurityGroupIds: !Ref SecurityGroupIds