
Parameters:
  AutoScalingGroupArn:
    Type: String

Resources:
  #
  # ECS - Capacity Provider
  #
  EC2CapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties: 
      AutoScalingGroupProvider: 
        AutoScalingGroupArn: !Ref AutoScalingGroupArn
        ManagedScaling: 
          InstanceWarmupPeriod: 120
          MaximumScalingStepSize: 20
          MinimumScalingStepSize: 1
          Status: ENABLED # DISABLED | ENABLED
          TargetCapacity: 100 # 1 ~ 100 (%)
        ManagedTerminationProtection: ENABLED # DISABLED | ENABLED
      # Name: String
      # Tags: 
      #   - Tag
  
  #
  # ECS - Cluster
  #
  Cluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: example-ecs-cluster
      CapacityProviders: 
        - !Ref EC2CapacityProvider
      ClusterSettings: 
        - Name: containerInsights
          Value: enabled
      Configuration: 
        ExecuteCommandConfiguration:
          Logging: DEFAULT # DEFAULT | NONE | OVERRIDE
      DefaultCapacityProviderStrategy: 
        - CapacityProvider: !Ref EC2CapacityProvider
          Weight: 100 # 1 ~ 1000
          Base: 0
