
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id


Resources:
  #
  # Security Groups
  #
  Example:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: description
      GroupName: example-sg
      Tags: 
        - Key: Name
          Value: example-sg
      VpcId: !Ref VpcId
    
  #
  # Ingress Rules
  #
  ExampleIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !Ref ExampleSecurityGroup
      # SourceSecurityGroupId: !Ref ExampleSecurityGroup
      # SourcePrefixListId: pl-63a5400a # you can check prefixlistID in console.
      CidrIp: 0.0.0.0/0
      IpProtocol: -1 # -1(all) , tcp , udp , icmp , icmpv6
      # ToPort: 443
      # FromPort: 443

  #
  # Egress Rules
  #
  ExampleEgress1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties: 
      GroupId: !Ref ExampleSecurityGroup
      # DestinationSecurityGroupId: !Ref ExampleSecurityGroup
      CidrIp: 0.0.0.0/0
      IpProtocol: -1 # -1(all) , tcp , udp , icmp , icmpv6
      # ToPort: 443
      # FromPort: 443
